### ISSUE TITLE
Is Jupiter config necessary?

### ISSUE THREAD

**Issue by jlink** [schmonz/junit-greencently#10]
In the readme you suggest to use

```
jvmArgs("-Djunit.jupiter.extensions.autodetection.enabled=true")
```

Since your extension is a JUnit platform hook (`TestExecutionListener`) this shouldn't be necessary.
It's registered in `src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener`.

**Comment by schmonz** [comment]
Thanks for the report! Makes sense that this could be correct. I'll test as soon as I can.
